/** Bump when PNG/SVG assets change so WebView2 does not serve stale launcher-icons. */
export const LAUNCHER_ICON_REV = '20';

/** Maps toolbar item ids to Icons8 3D Fluency PNGs (public/launcher-icons/). */
export const TOOLBAR_LAUNCHER_ICONS: Record<string, string> = {
  nav_back: 'nav_back.png',
  nav_forward: 'nav_forward.png',
  nav_up: 'nav_up.png',
  go_home: 'go_home.png',
  // Prefer PNG — multi-frame .ico often paints as a blank/white doc in WebView2 at 15–16px.
  home: 'go_home.png',
  refresh: 'refresh.png',
  folder_size_sync: 'folder_size_sync.png',
  go_recycle_bin: 'go_recycle_bin.png',
  go_network: 'go_network.png',
  new_tab: 'new_tab.png',
  cut: 'cut.png',
  copy: 'copy.png',
  paste: 'paste.png',
  delete: 'delete.png',
  undo: 'undo.png',
  redo: 'redo.png',
  select_all: 'select_all.png',
  invert_selection: 'invert_selection.png',
  copy_path: 'copy_path.png',
  copy_to: 'copy_to.png',
  new_folder: 'new_folder.png',
  new_file: 'new_file.png',
  compress: 'compress.png',
  extract: 'extract.png',
  properties: 'properties.png',
  sync_folders: 'sync_folders.png',
  map_network_drive: 'map_network_drive.png',
  share: 'Share.ico',
  burn_disc: 'burn_disc.png',
  view_details: 'view_details.png',
  view_grid: 'view_grid.png',
  view_list: 'view_list.png',
  view_columns: 'view_columns.png',
  search: 'search.png',
  toggle_dual_pane: 'toggle_dual_pane.svg',
  toggle_preview: 'toggle_preview.png',
  toggle_bottom: 'toggle_bottom.svg',
  smart_tools: 'smart_tools.png',
  tag_manager: 'tag_manager.png',
  accept: 'Accept.ico',
  decline: 'Decline.ico',
  icon_studio: 'icon_studio.png',
  find: 'find.png',
  dropstack: 'dropstack.png',
  filters: 'filters.png',
  batch_rename: 'batch_rename.png',
  shell_menus: 'shell_menus.png',
  metadata: 'metadata.png',
  storage_cleanup: 'storage_cleanup.png',
  sys_properties: 'sys_properties.png',
  config: 'config.png',
  extension_hub: 'extension_hub.png',
  wrench: 'wrench.png',
  cmd: 'cmd.png',
  ps: 'ps.png',
  terminal_here: 'terminal_here.png',
  taskmgr: 'taskmgr.png',
  regedit: 'regedit.png',
  control_panel: 'control_panel.png',
  settings_ui: 'control_panel.png',
  settings_app: 'settings_app.png',
  device_manager: 'device_manager.png',
  services: 'services.png',
  event_viewer: 'event_viewer.png',
  disk_mgmt: 'disk_mgmt.png',
  computer_mgmt: 'computer_mgmt.png',
  sysdm_cpl: 'sysdm_cpl.png',
  network_connections: 'network_connections.png',
  printers: 'printers.png',
  programs_features: 'programs_features.png',
  firewall: 'firewall.png',
  power_options: 'power_options.png',
  user_accounts: 'user_accounts.png',
  msinfo: 'msinfo.png',
  dxdiag: 'dxdiag.png',
  notepad: 'notepad.png',
  calc: 'calc.png',
  paint: 'paint.png',
  snipping_tool: 'snipping_tool.png',
  explorer: 'explorer.png',
  magnifier: 'magnifier.png',
  osk: 'osk.png',
  bookmark: 'bookmark.png',
  link: 'link.png',
  store: 'store.png',
  theme: 'theme.png',
  keyboard_settings: 'keyboard_settings.png',
  clipboard: 'clipboard.png',
  snippet: 'snippet.png',
  plugin: 'plugin.png',
  plugins: 'plugins.png',
  zip: 'zip.png',
  recycle: 'recycle.png',
  network: 'network.png',
  terminal: 'terminal.png',
  powershell: 'powershell.png',
  calculator: 'calculator.png',

  // Generic UI chrome — replaces Lucide app-wide (chevrons, close, check, spinner, etc.)
  chevron_right: 'chevron_right.png',
  chevron_left: 'chevron_left.png',
  chevron_down: 'chevron_down.png',
  chevron_up: 'chevron_up.png',
  close: 'close.png',
  check: 'check.png',
  star_ui: 'star_ui.png',
  clock_ui: 'clock_ui.png',
  loading: 'loading.png',
  warning: 'warning.png',
  error_ui: 'error_ui.png',
  external_link: 'external_link.png',
  send: 'send.png',
  upload: 'upload.png',
  download: 'download.png',
  plus_ui: 'plus_ui.png',
  minus_ui: 'minus_ui.png',
  lock_ui: 'lock_ui.png',
  unlock_ui: 'unlock_ui.png',
  shield_ui: 'shield_ui.png',
  key_ui: 'key_ui.png',
  database_ui: 'database_ui.png',
  sparkles_ui: 'sparkles_ui.png',
  pin_ui: 'pin_ui.png',
  pencil_ui: 'pencil_ui.png',
  picture_ui: 'picture_ui.png',
  music_ui: 'music_ui.png',
  film_ui: 'film_ui.png',
  code_ui: 'code_ui.png',
  info: 'Info.ico',
  info_ui: 'Info.ico',
  help_ui: 'help_ui.png',
  table_ui: 'table_ui.png',
  dashboard_ui: 'dashboard_ui.png',
  category_ui: 'category_ui.png',
  play_ui: 'play_ui.png',
  file_ui: 'file_ui.png',
  print_ui: 'print_ui.png',
  compare_ui: 'compare_ui.png',
  palette_ui: 'palette_ui.png',
  reset_ui: 'reset_ui.png',
  zap_ui: 'zap_ui.png',
  pointer_click_ui: 'pointer_click_ui.png',
  folder_open_ui: 'folder_open_ui.png',
  keyboard_ui: 'keyboard_ui.png',
  mouse_ui: 'mouse_ui.png',
  trash_ui: 'trash_ui.png',
  layers_ui: 'layers_ui.png',
  eye_ui: 'eye_ui.png',
  // No distinct Icons8 3D-fluency "eye slash" asset resolves reliably; reuse the eye
  // glyph — call sites differentiate state via opacity/tooltip, not the icon shape.
  eye_off_ui: 'eye_ui.png',
  puzzle_ui: 'puzzle_ui.png',
  globe_ui: 'globe_ui.png',
  filter_ui: 'filter_ui.png',
  arrow_right_ui: 'arrow_right_ui.png',
  monitor_ui: 'monitor_ui.png',
  this_pc: 'computer_mgmt.png',
  cloud_ui: 'cloud_ui.png',
  cloud_drive: 'Cloud-drive.ico',
  git_branch_ui: 'git_branch_ui.png',
  hard_drive_ui: 'hard_drive_ui.png',
  history_ui: 'history_ui.png',
  eraser_ui: 'eraser_ui.png',
  file_search_ui: 'file_search_ui.png',
  zoom_in_ui: 'color-zoom-in.svg',
  zoom_out_ui: 'color-zoom-out.svg',
  maximize_ui: 'maximize_ui.png',
  target_ui: 'target_ui.png',
  regex_ui: 'regex_ui.png',
  braces_ui: 'braces_ui.png',
  wand_ui: 'wand_ui.png',
  command_ui: 'command_ui.png',
  images_ui: 'images_ui.png',
  rocket_ui: 'rocket_ui.png',
  piechart_ui: 'piechart_ui.png',
  move_ui: 'move_ui.png',
  bookopen_ui: 'bookopen_ui.png',
  magnet_ui: 'magnet_ui.png',
  radio_ui: 'radio_ui.png',
  volume_ui: 'volume_ui.png',
  volume_off_ui: 'volume_off_ui.png',
  skip_back_ui: 'skip_back_ui.png',
  skip_forward_ui: 'skip_forward_ui.png',
  pause_ui: 'pause_ui.png',
  brain_ui: 'brain_ui.png',
  wifi_off_ui: 'wifi_off_ui.png',
  folder_plus_ui: 'folder_plus_ui.png',
  server_ui: 'server_ui.png',
  play_circle_ui: 'play_circle_ui.png',
  arrow_down_circle_ui: 'arrow_down_circle_ui.png',
  checksquare_ui: 'checksquare_ui.png',
  columns_ui: 'columns_ui.png',
  mini_tree: 'mini_tree.png',
  scissors_ui: 'scissors_ui.png',
  panel_bottom_ui: 'panel_bottom_ui.png',
  // New launcher SVGs (emblems / media)
  bluetooth: 'bluetooth.svg',
  emblem_added: 'emblem-added.svg',
  emblem_checked: 'emblem-checked.svg',
  emblem_documents: 'emblem-documents.svg',
  emblem_downloads: 'emblem-downloads.svg',
  emblem_shared: 'emblem-shared.svg',
  emblem_symbolic_link: 'emblem-symbolic-link.svg',
  emblem_synchronizing: 'emblem-synchronizing.svg',
  emblem_unlocked: 'emblem-unlocked.svg',
  media_playback_playing: 'media-playback-playing.svg',
  media_playback_paused: 'media-playback-paused.svg',
  media_playback_stop: 'media-playback-stop.svg',
  media_record: 'media-record.svg',
  media_repeat_none: 'media-repeat-none.svg',
  media_repeat_single: 'media-repeat-single.svg',
  media_seek_backward: 'media-seek-backward.svg',
  media_seek_forward: 'media-seek-forward.svg',
  media_skip_backward: 'media-skip-backward.svg',
  media_skip_forward: 'media-skip-forward.svg',
  // Ui/ chrome assets (public/Ui/)
  ui_plugin: 'Ui/plugin.svg',
  ui_color: 'Ui/color.svg',
  ui_icons: 'Ui/icons.svg',
  ui_keyboard: 'Ui/keybinds-keyboard.svg',
  ui_featured: 'Ui/applications-featured.svg',
  ui_image_loading: 'Ui/image-loading.svg',
  ui_image_missing: 'Ui/image-missing.svg',
  ui_preview_folder: 'Ui/preview-Big Folder.svg',
  ui_preview_folder_alt: 'Ui/preview-Big Folder-1.svg',
};

/** Custom assets that must not be overwritten by the Icons8 downloader. */
export const CUSTOM_LAUNCHER_ICON_IDS = new Set([
  'toggle_dual_pane',
  'toggle_bottom',
  'tag_manager',
  'favorites',
  'accept',
  'decline',
  'zoom_in_ui',
  'zoom_out_ui',
  'home',
  'this_pc',
  'cloud_drive',
  'share',
  'info',
  'info_ui',
]);

/** Icon ids that render fine at small (≤16px) sizes without becoming illegible 3D-render mush. */
export const UI_GLYPH_IDS = new Set([
  'chevron_right', 'chevron_left', 'chevron_down', 'chevron_up', 'close', 'check',
  'star_ui', 'clock_ui', 'loading', 'warning', 'error_ui', 'external_link', 'send',
  'upload', 'download', 'plus_ui', 'minus_ui', 'lock_ui', 'unlock_ui', 'shield_ui',
  'key_ui', 'database_ui', 'sparkles_ui', 'pin_ui', 'pencil_ui', 'picture_ui', 'music_ui',
  'film_ui', 'code_ui', 'info', 'info_ui', 'help_ui', 'table_ui', 'dashboard_ui', 'category_ui',
  'play_ui', 'palette_ui', 'reset_ui', 'zap_ui', 'pointer_click_ui', 'folder_open_ui',
  'keyboard_ui', 'mouse_ui', 'trash_ui', 'layers_ui', 'eye_ui', 'eye_off_ui', 'puzzle_ui',
  'globe_ui', 'filter_ui', 'arrow_right_ui', 'monitor_ui', 'this_pc', 'cloud_ui', 'cloud_drive',
  'git_branch_ui',
  'hard_drive_ui', 'history_ui', 'eraser_ui', 'file_search_ui', 'zoom_in_ui', 'zoom_out_ui',
  'maximize_ui', 'target_ui', 'regex_ui', 'braces_ui', 'wand_ui', 'command_ui', 'images_ui',
  'rocket_ui', 'piechart_ui', 'move_ui', 'bookopen_ui', 'magnet_ui', 'radio_ui', 'volume_ui',
  'volume_off_ui', 'skip_back_ui', 'skip_forward_ui', 'pause_ui', 'brain_ui', 'wifi_off_ui',
  'folder_plus_ui', 'server_ui', 'play_circle_ui', 'arrow_down_circle_ui', 'checksquare_ui',
  'columns_ui', 'scissors_ui', 'panel_bottom_ui', 'mini_tree', 'tag_manager', 'favorites',
  'accept', 'decline',
  'toggle_dual_pane', 'toggle_bottom', 'home', 'share',
  'bluetooth', 'emblem_added', 'emblem_checked', 'emblem_documents', 'emblem_downloads',
  'emblem_shared', 'emblem_symbolic_link', 'emblem_synchronizing', 'emblem_unlocked',
  'media_playback_playing', 'media_playback_paused', 'media_playback_stop', 'media_record',
  'media_repeat_none', 'media_repeat_single', 'media_seek_backward', 'media_seek_forward',
  'media_skip_backward', 'media_skip_forward',
  'ui_plugin', 'ui_color', 'ui_icons', 'ui_keyboard', 'ui_featured',
  'ui_image_loading', 'ui_image_missing', 'ui_preview_folder', 'ui_preview_folder_alt',
]);

export function launcherIconUrl(id: string): string | undefined {
  const base = id.startsWith('tag__') ? 'tag_manager' : id;
  const file = TOOLBAR_LAUNCHER_ICONS[base];
  if (!file) return undefined;
  if (file.startsWith('Ui/')) return `/${file}?v=${LAUNCHER_ICON_REV}`;
  return `/launcher-icons/${file}?v=${LAUNCHER_ICON_REV}`;
}
