# Downloads Icons8 3D Fluency PNGs for BNDZ toolbar + configurator.
# Source: https://icons8.com/icons/all--technique-3d (free with attribution)
param([string]$Root = "", [int]$Size = 48)

$ErrorActionPreference = "Stop"
if (-not $Root) {
    $Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
}

$dest = Join-Path $Root "public\launcher-icons"
New-Item -ItemType Directory -Path $dest -Force | Out-Null

# toolbar id -> Icons8 3d-fluency slug
$map = @{
    nav_back = 'arrow-left'
    nav_forward = 'arrow-right'
    nav_up = 'arrow-up'
    go_home = 'home'
    refresh = 'refresh'
    folder_size_sync = 'bar-chart'
    go_recycle_bin = 'trash-can'
    go_network = 'globe'
    new_tab = 'add-file'
    cut = 'cut'
    copy = 'documents'
    paste = 'paste'
    delete = 'trash'
    undo = 'undo'
    redo = 'redo'
    select_all = 'checkmark'
    invert_selection = 'synchronize'
    copy_path = 'link'
    copy_to = 'upload'
    new_folder = 'add-folder'
    new_file = 'add-file'
    compress = 'archive'
    extract = 'archive'
    properties = 'info'
    sync_folders = 'synchronize'
    map_network_drive = 'globe'
    share = 'link'
    burn_disc = 'cd'
    view_details = 'view'
    view_grid = 'icons'
    view_list = 'menu'
    view_columns = 'flow-chart'
    search = 'search'
    toggle_dual_pane = 'module'
    toggle_preview = 'opened-folder'
    toggle_bottom = 'layers'
    smart_tools = 'sparkles'
    tag_manager = 'price-tag'
    icon_studio = 'color-palette'
    find = 'magnifying-glass'
    dropstack = 'stack'
    mini_tree = 'oak-tree'
    filters = 'filter'
    batch_rename = 'edit'
    shell_menus = 'menu'
    metadata = 'database'
    storage_cleanup = 'broom'
    sys_properties = 'information'
    config = 'gear'
    extension_hub = 'shop'
    wrench = 'wrench'
    cmd = 'command-line'
    ps = 'code'
    terminal_here = 'console'
    taskmgr = 'processor'
    regedit = 'database'
    control_panel = 'control-panel'
    settings_app = 'windows-10'
    device_manager = 'device-manager'
    services = 'services'
    event_viewer = 'book'
    disk_mgmt = 'hdd'
    computer_mgmt = 'monitor'
    sysdm_cpl = 'information'
    network_connections = 'wifi'
    printers = 'print'
    programs_features = 'shop'
    firewall = 'firewall'
    power_options = 'battery'
    user_accounts = 'group'
    msinfo = 'information'
    dxdiag = 'joystick'
    notepad = 'notepad'
    calc = 'calculator'
    paint = 'paint-brush'
    snipping_tool = 'camera'
    explorer = 'opened-folder'
    magnifier = 'magnifying-glass'
    osk = 'keyboard'
    bookmark = 'bookmark'
    link = 'link'
    store = 'shop'
    theme = 'color-palette'
    keyboard_settings = 'keyboard'
    clipboard = 'paste'
    snippet = 'note'
    plugin = 'plugin'
    plugins = 'puzzle'
    zip = 'archive'
    recycle = 'trash-can'
    network = 'globe'
    terminal = 'command-line'
    powershell = 'code'
    calculator = 'calculator'

    # Generic UI chrome glyphs (chevrons, close, check, spinner, etc.) — replaces Lucide
    # imports app-wide. Every slug below is verified to return HTTP 200 from the CDN.
    chevron_right = 'forward'
    chevron_left = 'back'
    chevron_down = 'down'
    chevron_up = 'up'
    close = 'cancel'
    check = 'checkmark'
    star_ui = 'star'
    clock_ui = 'clock'
    loading = 'loading'
    warning = 'warning-shield'
    error_ui = 'error'
    external_link = 'link'
    send = 'paper-plane'
    upload = 'upload'
    download = 'download'
    plus_ui = 'plus'
    minus_ui = 'minus'
    lock_ui = 'lock'
    unlock_ui = 'unlock'
    shield_ui = 'shield'
    key_ui = 'key'
    database_ui = 'database'
    sparkles_ui = 'sparkles'
    pin_ui = 'pin'
    pencil_ui = 'pencil'
    picture_ui = 'picture'
    music_ui = 'music'
    film_ui = 'film-reel'
    code_ui = 'code'
    info_ui = 'info'
    help_ui = 'help'
    table_ui = 'table'
    dashboard_ui = 'dashboard'
    category_ui = 'category'
    play_ui = 'play'
    file_ui = 'document'
    print_ui = 'print'
    compare_ui = 'scales'
    palette_ui = 'color-palette'
    reset_ui = 'refresh'
    zap_ui = 'flash-on'
    pointer_click_ui = 'cursor'
    folder_open_ui = 'opened-folder'
    keyboard_ui = 'keyboard'
    mouse_ui = 'mouse'
    trash_ui = 'trash'
    layers_ui = 'stack'
    eye_ui = 'eye'
    puzzle_ui = 'puzzle'
    globe_ui = 'globe'
    filter_ui = 'filter'
    arrow_right_ui = 'arrow-right'
    monitor_ui = 'monitor'
    cloud_ui = 'cloud'
    git_branch_ui = 'source-code'
    hard_drive_ui = 'hdd'
    history_ui = 'clock'
    eraser_ui = 'broom'
    file_search_ui = 'document'
    zoom_in_ui = 'magnifying-glass'
    zoom_out_ui = 'magnifying-glass'
    maximize_ui = 'view'
    target_ui = 'goal'
    regex_ui = 'code'
    braces_ui = 'code'
    wand_ui = 'sparkles'
    command_ui = 'command-line'
    images_ui = 'picture'
    rocket_ui = 'rocket'
    piechart_ui = 'pie-chart'
    move_ui = 'cursor'
    bookopen_ui = 'open-book'
    magnet_ui = 'magnet'
    radio_ui = 'radio'
    volume_ui = 'music'
    volume_off_ui = 'cancel'
    skip_back_ui = 'back'
    skip_forward_ui = 'forward'
    brain_ui = 'brain'
    wifi_off_ui = 'wifi-off'
    folder_plus_ui = 'add-folder'
    server_ui = 'server'
    play_circle_ui = 'play'
    arrow_down_circle_ui = 'arrow-down'
    checksquare_ui = 'checked-checkbox'
    columns_ui = 'table'
    scissors_ui = 'cut'
    panel_bottom_ui = 'stack'
}

$base = "https://img.icons8.com/3d-fluency/$Size"
$ok = 0
$fail = 0

foreach ($pair in $map.GetEnumerator()) {
    $out = Join-Path $dest "$($pair.Key).png"
    $url = "$base/$($pair.Value).png"
    try {
        Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing -TimeoutSec 20
        $ok++
    }
    catch {
        Write-Warning "Failed $($pair.Key) <- $($pair.Value)"
        $fail++
    }
}

Write-Host "==> Icons8 3D toolbar icons: $ok ok, $fail failed -> $dest" -ForegroundColor Green
