#Requires -Version 5.1
<#
.SYNOPSIS
  Package BNDZ-Native (WinUI BNDZShell) as portable zip + Inno Setup installer.

  Ship binary is Native only - never classic WPF dist\BNDZ-Setup-*.exe as "Native".

  Release needs BNDZ_LICENSE_SECRET + BNDZ_TOKEN_HMAC_SECRET (same as build-release.ps1).
  If those are unset, defaults to Debug Launch Ready beta packaging.
#>
param(
  [string]$Configuration = '',
  [string]$Version = '1.0.0',
  [switch]$SkipBuild,
  [switch]$SkipInstaller,
  [switch]$RequireRelease
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Get-Iscc {
  @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe"
  ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}

function Test-RetailSecretsPresent {
  $lic = $env:BNDZ_LICENSE_SECRET
  $tok = $env:BNDZ_TOKEN_HMAC_SECRET
  if (-not $lic -or $lic -eq 'BNDZ-36-Commercial-Key-Seed-CHANGE-ME') { return $false }
  if (-not $tok) { return $false }
  return $true
}

function Write-ReleaseSecretEmbeds {
  $backend = Join-Path $root 'BNDZBackend'
  $secret = $env:BNDZ_LICENSE_SECRET
  $escaped = $secret.Replace('\', '\\').Replace('"', '\"')
  $licSource = @"
// AUTO-GENERATED by scripts/package-bndz-native.ps1 — do not commit.
namespace BNDZ.Services;

internal static class LicenseSecretEmbedded
{
    public const string Value = "$escaped";
}
"@
  Set-Content -Path (Join-Path $backend 'Services\LicenseSecretEmbedded.Release.cs') -Value $licSource -Encoding UTF8

  $tokenSecret = $env:BNDZ_TOKEN_HMAC_SECRET
  $tokEscaped = $tokenSecret.Replace('\', '\\').Replace('"', '\"')
  $tokSource = @"
// AUTO-GENERATED by scripts/package-bndz-native.ps1 — do not commit.
namespace BNDZ.Services;

internal static class LicenseTokenSecretEmbedded
{
    public const string Value = "$tokEscaped";
}
"@
  Set-Content -Path (Join-Path $backend 'Services\LicenseTokenSecretEmbedded.Release.cs') -Value $tokSource -Encoding UTF8
  Write-Host '==> Embedded retail license + token HMAC secrets for Release' -ForegroundColor Yellow
}

if ([string]::IsNullOrWhiteSpace($Configuration)) {
  if (Test-RetailSecretsPresent) {
    $Configuration = 'Release'
  } else {
    if ($RequireRelease) {
      throw 'RequireRelease set but BNDZ_LICENSE_SECRET / BNDZ_TOKEN_HMAC_SECRET missing or placeholder.'
    }
    $Configuration = 'Debug'
    Write-Host '==> No retail secrets in env — packaging Debug Launch Ready beta' -ForegroundColor Yellow
    Write-Host '    Set BNDZ_LICENSE_SECRET + BNDZ_TOKEN_HMAC_SECRET for retail Release.' -ForegroundColor DarkGray
  }
} elseif ($Configuration -eq 'Release') {
  if (-not (Test-RetailSecretsPresent)) {
    throw 'Release packaging needs BNDZ_LICENSE_SECRET (non-placeholder) and BNDZ_TOKEN_HMAC_SECRET.'
  }
}

$dist = Join-Path $root 'dist'
$publish = Join-Path $dist 'publish\bndz-native-win-x64'
$zipName = if ($Configuration -eq 'Debug') {
  "BNDZ-Native-win-x64-portable-$Version-debug.zip"
} else {
  "BNDZ-Native-win-x64-portable-$Version.zip"
}
$zipPath = Join-Path $dist $zipName
$setupBase = if ($Configuration -eq 'Debug') {
  "BNDZ-Native-Setup-$Version-debug"
} else {
  "BNDZ-Native-Setup-$Version"
}
$setupOut = Join-Path $dist "$setupBase.exe"
$iss = Join-Path $root 'installer\BNDZ-Native.iss'
$redist = Join-Path $root 'installer\redist'
$wv2 = Join-Path $redist 'MicrosoftEdgeWebview2Setup.exe'
$wv2Url = 'https://go.microsoft.com/fwlink/p/?LinkId=2124703'

Write-Host "==> Package BNDZ-Native ($Configuration v$Version)" -ForegroundColor Cyan

foreach ($n in @('BNDZ','BNDZShell')) {
  Get-Process -Name $n -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue
  cmd /c "taskkill /F /IM $n.exe /T >nul 2>nul"
}
Start-Sleep -Milliseconds 800

if (-not $SkipBuild) {
  if ($Configuration -eq 'Release') { Write-ReleaseSecretEmbeds }

  Write-Host '==> Frontend (npm run build)' -ForegroundColor Cyan
  $prevEap = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  cmd /c "npm run build > tmp_npm_build_pkg.txt 2>&1"
  $npmExit = $LASTEXITCODE
  $ErrorActionPreference = $prevEap
  if ($npmExit -ne 0) {
    Get-Content tmp_npm_build_pkg.txt -Tail 40 -ErrorAction SilentlyContinue
    throw "npm run build failed ($npmExit)"
  }

  Write-Host "==> Backend + Shell ($Configuration x64)" -ForegroundColor Cyan
  dotnet build (Join-Path $root 'BNDZBackend\BNDZ.csproj') -c $Configuration -p:EnableWindowsTargeting=true
  $be = $LASTEXITCODE
  if ($be -ne 0) { $ErrorActionPreference = $prevEap; throw 'backend build failed' }
  dotnet build (Join-Path $root 'BNDZShell\src\BNDZShell.App\BNDZShell.App.csproj') -c $Configuration -p:Platform=x64 -p:EnableWindowsTargeting=true
  $sh = $LASTEXITCODE
  $ErrorActionPreference = $prevEap
  if ($sh -ne 0) { throw 'shell build failed' }
}

$binRoot = Join-Path $root "BNDZShell\src\BNDZShell.App\bin\x64\$Configuration"
$outDir = Get-ChildItem -Path $binRoot -Directory -Recurse -Filter 'net*-windows*' -EA SilentlyContinue |
  Where-Object { Test-Path (Join-Path $_.FullName 'BNDZ.exe') } |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

if (-not $outDir) { throw "No BNDZ.exe under $binRoot" }
Write-Host "  source: $($outDir.FullName)" -ForegroundColor DarkGray

if (Test-Path $publish) { Remove-Item $publish -Recurse -Force }
New-Item -ItemType Directory -Path $publish -Force | Out-Null
& robocopy $outDir.FullName $publish /MIR /NFL /NDL /NJH /NJS /nc /ns /np | Out-Null
if ($LASTEXITCODE -ge 8) { throw "robocopy failed ($LASTEXITCODE)" }
$LASTEXITCODE = 0

if (-not (Test-Path (Join-Path $publish 'BNDZ.exe'))) { throw 'BNDZ.exe missing in publish folder' }
if (-not (Test-Path (Join-Path $publish 'Assets\ui'))) {
  Write-Host '  syncing Assets\ui into publish' -ForegroundColor Yellow
  $uiSrc = Join-Path $root 'BNDZBackend\Assets\ui'
  $uiDst = Join-Path $publish 'Assets\ui'
  New-Item -ItemType Directory -Path (Split-Path $uiDst) -Force | Out-Null
  & robocopy $uiSrc $uiDst /MIR /NFL /NDL /NJH /NJS /nc /ns /np | Out-Null
  if ($LASTEXITCODE -ge 8) { throw "ui robocopy failed ($LASTEXITCODE)" }
  $LASTEXITCODE = 0
}

Write-Host '==> Portable zip' -ForegroundColor Cyan
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $publish '*') -DestinationPath $zipPath -CompressionLevel Optimal
Write-Host "  $zipPath ($([math]::Round((Get-Item $zipPath).Length/1MB,1)) MB)" -ForegroundColor Green

if ($SkipInstaller) {
  Write-Host '==> SkipInstaller set' -ForegroundColor DarkGray
  Write-Host "Ready: $zipPath"
  exit 0
}

$iscc = Get-Iscc
if (-not $iscc) { throw 'Inno Setup 6 ISCC.exe not found' }

if (-not (Test-Path $redist)) { New-Item -ItemType Directory -Path $redist -Force | Out-Null }
if (-not (Test-Path $wv2) -or ((Get-Item $wv2).Length -lt 1MB)) {
  Write-Host '==> Downloading WebView2 bootstrapper' -ForegroundColor Yellow
  Invoke-WebRequest -Uri $wv2Url -OutFile $wv2 -UseBasicParsing
}

if (-not (Test-Path $iss)) { throw "Missing $iss" }

Write-Host '==> Inno Setup (BNDZ-Native)' -ForegroundColor Cyan
& $iscc $iss "/DPublishDir=$publish" "/DMyAppVersion=$Version" "/DSourcePath=$root" "/DOutputBaseFilename=$setupBase"
if ($LASTEXITCODE -ne 0) {
  # Older iss may ignore OutputBaseFilename define — rewrite via /F if needed
  & $iscc $iss "/DPublishDir=$publish" "/DMyAppVersion=$Version" "/DSourcePath=$root"
  if ($LASTEXITCODE -ne 0) { throw "ISCC failed ($LASTEXITCODE)" }
}

if (-not (Test-Path $setupOut)) {
  $found = Get-ChildItem (Join-Path $dist 'BNDZ-Native-Setup-*.exe') -EA SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
  if ($found) { $setupOut = $found.FullName }
}
Write-Host "==> Installer: $setupOut" -ForegroundColor Green
Write-Host "==> Portable: $zipPath" -ForegroundColor Green
if ($Configuration -eq 'Debug') {
  Write-Host 'Debug Launch Ready beta — not retail-licensed Release. Unsigned; SmartScreen may warn.' -ForegroundColor DarkYellow
} else {
  Write-Host 'Unsigned Native Release — SmartScreen may warn until Authenticode is wired.' -ForegroundColor DarkYellow
}
